[package]
name = "scheduler"
version = "0.1.0"
authors = ["Christian Waldron <cwaldro5@msudenver.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "5.0"
rand = "0.7"
rust-argon2 = "0.8"